mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=steamservice
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

mongo:
  image: mongo

app:
  image: openjdk:8-jdk-alpine
  ports:
    - "443:443"
  environment:
      - SPRING_PROFILE=docker
  links:
    - mysql
    - mongo
  volumes:
    - ./config:/config
    - ./build/libs:/app
  command: java -jar ./app/gs.jar